### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MOOOOs** [CookieGD/Not-Enough-Trinket-Slots-NETS-#1]
Hey i stared using your mod but there is a thing that Bunch o' Trinkets is outdated and i can't use these slots your mod has do you know any alternative out somewhere to use slots that Bunch o' Trinkets used?
sorry if it meant for bugs only but there is alot of missing without that mod

**Comment by CookieGD** [comment]
Heyy, sry I never used Bunch o' Trinkets before and idk how to add support for it. I wish I could help you out but idk how :/
