### ISSUE TITLE
Can be marked as 1.20.2 compatible

### ISSUE THREAD

**Issue by sternschnaube** [CookieGD/Not-Enough-Trinket-Slots-NETS-#3]

**Comment by sternschnaube** [comment]
I tested the mod along with Polymer Trinkets port, everything loads fine and seems to work.
https://modrinth.com/mod/trinkets-polymer

You could verify and mark the mod compatible for 1.20.2 on Modrinth 😄

**Comment by CookieGD** [comment]
Oh god I have to check my mails more often. I have a version on CF that is compatible with 1.20.2-4 but I forgot to upload it to modrinth 😅
